project:
  type: website

resources:
  - "static/*"

website:
  title: "CCMI"
  description: "EPSRC Centre for Doctoral Training in Colllaborative Computational Modelling at the Interface"
  favicon: static/assets/ccmi_rounded_colour.png
  open-graph: true

  navbar:
    background: darkblue
    logo: static/assets/ccmi_rounded_colour.png
    search: true
    right:
      - text: Home
        file: index.qmd
      - text: Events
        file: events/event_list.qmd
      - text: Training Programme
        file: training/training.qmd

      - text: How to apply
        file: apply.qmd

      - text: Blog
        file: blog/blog_list.qmd

      - text: FAQ
        file: faq.qmd

      - text: About
        menu:
          - text: Current Students
            file: student_list.qmd
          - text: Our Leadership Team
            file: team.qmd
          - text: Contact us
            href: /#contact-us

format:
  html:
    theme: default
    css: styles.css
    toc: false
    smooth-scrolling: true
    font-family: sans-serif
    include-after-body: "templates/footer.html"

execute:
  freeze: auto
